const express=require('express');
const router=express.Router();
const Sales=require('../controllers/Sales');
const Receipt=require('../controllers/Reciept');
const Purchases=require('../controllers/Purchases');
const chat =require('../controllers/Chat');
// const fileUpload = require("express-fileupload");
const Stocks=require('../controllers/Stocks');
const Admin=require('../controllers/Admin');
const Debtors=require('../controllers/Debtors');
const User=require('../controllers/User');
const Creditsales=require('../controllers/CreditSales');
const Supplier=require('../controllers/Supplier');
const Account=require('../controllers/Account');
const Search=require('../controllers/Search');
const session=require("express-session");
router.use(session({secret: 'ssshhhhh',saveUninitialized: true,resave: true}));
// router.use(fileUpload({
//     useTempFiles : true,
//     tempFileDir : '/tmp/'
//   }));
const flash=require("connect-flash");
const bodyparser = require('body-parser');
router.use(bodyparser.urlencoded({extended:false}));
router.use(bodyparser.json());
router.use(flash());
router.post('/sales',Sales.postSales);
router.get('/sales',Sales.getSales);
router.post('/retail',Sales.postRetail);
router.get('/retail',Sales.getRetail);
router.get('/userviewpurchases',Purchases.viewUserPurchases);
router.post('/userviewpurchases',Purchases.postviewUserPurchases);
router.get('/allstocks',Stocks.allStocks);
router.post('/allstocks',Stocks.postAllstocks);
router.get('/adminhome',Admin.Admin);
router.post('/purchases',Purchases.postPurchases);
router.get('/purchases',Purchases.getPurchases);
router.post('/searchdebtors',Debtors.searchDebtors);
router.post('/alldebtors',Debtors.allDebtors);
router.get('/alldebtors',Debtors.getAllDebtors);
router.get('/creditsales',Creditsales.getCreditSales);
router.get('/creditretailsales',Creditsales.getCreditRetailSales);
router.post('/creditsales',Creditsales.postCreditSales);
router.get('/additems',Stocks.getaddItems);
router.post('/additems',Stocks.postAdditems);
router.post('/creditretailsales',Creditsales.postCreditRetailSales);
router.get('/admininformation:id',Admin.getAdminInformation);
router.get('/information:id',User.userInformation);
router.get('/supplierinformation:id',Supplier.supplierInformation);
router.get('/supplieradmininformation:id',Supplier.supplierAdminInformation);
router.post('/admindailysales',Admin.adminDailySales);
router.post('/dailysales',User.userDailySales);
router.get('/debtorsinformation:id',Debtors.getDebtorsInformation);
router.get('/userhome',User.getUserHome);
router.get('/debtorsedit:id',Debtors.getDebtorsEdit);
router.post('/debtorsedit:id',Debtors.postDebtorsEdit);
router.get('/suppliersedit:id',Supplier.getSuppliersEdit)
router.get('/suppliersadminedit:id',Supplier.getSuppliersAdminEdit);
router.post('/suppliersedit:id',Supplier.postSupplierEdit);
router.post('/suppliersadminedit:id',Supplier.postSupplierAdminEdit);
router.get('/edit:id',User.Edit);
router.get('/adminitemsedit:id',Admin.getAdminItemsEdit);
router.post('/adminitemsedit:id',Admin.postAdminItemsEdit);
router.post('/edit:id',User.postEdit);
router.post('/userlogin',User.postUserLogin);
router.get('/adminitemsdelete:id',Admin.getAdminDelete);
router.get('/supplier',Supplier.getSupplier);
router.post('/adminsupplier',Supplier.postadminSupplier);
router.get('/adminsupplier',Supplier.getadminSupplier);
router.get('/admin',Admin.getadmin);
router.post('/supplier',Supplier.postSupplier);
router.get('/allsuppliers',Supplier.getAllSuppliers);
router.get('/allsuppliersadmin',Supplier.getAllSuppliersAdmin);
router.get('/forgotadminpassword',Account.forgotAdminPassword);
router.post('/forgotadminpassword',Account.PostforgotAdminPassword);
router.get('/adminchangepassword:id',Account.getAdminChangePassword);
router.post('/adminchangepassword:id',Account.postAdminChangePassword);
router.get('/forgotuserpassword',Account.getuserForgotPassword);
router.post('forgotuserpassword',Account.postuserForgotPassword);
router.post('/createuser',Account.postcreateUser);
router.get('/createuser',Account.getCreateUser);
router.get('/userlogin',User.getuserLogin);
router.get('/signupandsignin',User.getSignupandsignin);
router.post('/adminsearch',Admin.AdminSearch);
router.post('/allsuppliersadmin',Supplier.postAllsupplierAdmin);
router.post('/allusers',User.postAllusers);
router.post('/allsuppliers',Supplier.postAllsuppliers);
router.get('/viewpurchases',Purchases.getviewPurchases);
router.get('/usersdelete:id',User.usersDelete);
router.get('/debtorsdelete:id',Debtors.debtorsDelete);
router.get('/suppliersdelete:id',Supplier.getsuppliersDelete);
router.get('/printreceipt',Receipt.getPrintReceipt);
router.get('/printreceiptadmin',Receipt.printreceiptAdmin);
router.get('/search',Receipt.searchReciept);
router.get('/adminsearch',Receipt.adminReceipt);
router.post('/search',Search.postSearch);
router.post('/see',Admin.postSignUp);
router.post('/admin',Admin.logAdmin);
router.get('/adminhome',Admin.adminHome);
router.post('/accounteditinfo:id',Account.acccountEditId);
router.get('/accounteditinfo:id',Account.getAccountEdit);
router.get('/useraccountedit:id',User.userAccountEdit);
router.post('/useraccountedit:id',User.postuserAccountEdit);
router.get('/userpasswordchange:id',User.getuserPasswordChange);
router.post('/userpasswordchange:id',User.postuserPasswordChange);
router.get('/allusers',User.getAllUsers);
router.get('/admindailysales',Sales.adminGetDailySales);
router.get('/dailysales',Sales.getDailySales);
router.get('/logout',User.logout);
router.get('/delete:id',Purchases.deletePurchases);
router.get('/checkpage',User.checkPage);
router.get('/',User.home);
router.get('/chat',chat.Chats);
module.exports=router;