const express = require('express');
const router = express.Router();
const Sales = require('../controllers/Sales');
const Receipt = require('../controllers/Reciept');
const Purchases = require('../controllers/Purchases');
const chat = require('../controllers/Chat');
// const fileUpload = require("express-fileupload");
const Stocks = require('../controllers/Stocks');
const Admin = require('../controllers/Admin');
const Debtors = require('../controllers/Debtors');
// const RoleAuth = require('../middleware/Role');
const User = require('../controllers/User');
const Creditsales = require('../controllers/CreditSales');
const Supplier = require('../controllers/Supplier');
const Account = require('../controllers/Account');
const Search = require('../controllers/Search');
const session = require("express-session");
router.use(session({ secret: 'ssshhhhh', saveUninitialized: true, resave: true }));
const checkAuth = require('../middleware/user');
const dashBoardAuth = require('../middleware/dashboard');
// router.use(fileUpload({
//     useTempFiles : true,
//     tempFileDir : '/tmp/'
//   }));
const flash = require("connect-flash");
const bodyparser = require('body-parser');
const RoleAuth = require('../middleware/Role');
router.use(bodyparser.urlencoded({ extended: false }));
router.use(bodyparser.json());
router.use(flash());
router.post('/sales', checkAuth, Sales.postSales);
router.get('/sales', checkAuth, Sales.getSales);
router.post('/retail', checkAuth, Sales.postRetail);
router.get('/retail', checkAuth, Sales.getRetail);
router.get('/userviewpurchases', checkAuth, Purchases.viewUserPurchases);
router.post('/userviewpurchases', checkAuth, Purchases.postviewUserPurchases);
router.get('/allstocks', checkAuth, Stocks.allStocks);
router.post('/allstocks', checkAuth, Stocks.postAllstocks);
router.post('/purchases', checkAuth, Purchases.postPurchases);
router.get('/purchases', checkAuth, Purchases.getPurchases);
router.post('/searchdebtors', checkAuth, Debtors.searchDebtors);
router.post('/alldebtors', checkAuth, Debtors.allDebtors);
router.get('/alldebtors', checkAuth, Debtors.getAllDebtors);
router.get('/creditsales', checkAuth, Creditsales.getCreditSales);
router.get('/creditretailsales', checkAuth, Creditsales.getCreditRetailSales);
router.post('/creditsales', checkAuth, Creditsales.postCreditSales);
router.get('/additems', checkAuth, Stocks.getaddItems);
router.post('/additems', checkAuth, Stocks.postAdditems);
router.post('/creditretailsales', checkAuth, Creditsales.postCreditRetailSales);
router.get('/admininformation:id', checkAuth, Admin.getAdminInformation);
router.get('/information:id', checkAuth, User.userInformation);
router.get('/supplierinformation:id', checkAuth, Supplier.supplierInformation);
router.get('/supplieradmininformation:id', checkAuth, Supplier.supplierAdminInformation);
router.post('/admindailysales', checkAuth, Admin.adminDailySales);
router.post('/dailysales', checkAuth, User.userDailySales);
router.get('/debtorsinformation:id', checkAuth, Debtors.getDebtorsInformation);
router.get('/userhome', checkAuth, User.getUserHome);
router.get('/debtorsedit:id', checkAuth, Debtors.getDebtorsEdit);
router.post('/debtorsedit:id', checkAuth, Debtors.postDebtorsEdit);
router.get('/suppliersedit:id', checkAuth, Supplier.getSuppliersEdit)
router.get('/suppliersadminedit:id', checkAuth, Supplier.getSuppliersAdminEdit);
router.post('/suppliersedit:id', checkAuth, Supplier.postSupplierEdit);
router.post('/suppliersadminedit:id', checkAuth, Supplier.postSupplierAdminEdit);
router.get('/edit:id', checkAuth, User.Edit);
router.get('/adminitemsedit:id', checkAuth, Admin.getAdminItemsEdit);
router.post('/adminitemsedit:id', checkAuth, Admin.postAdminItemsEdit);
router.post('/edit:id', checkAuth, User.postEdit);
router.post('/userlogin', User.postUserLogin);
router.get('/adminitemsdelete:id', checkAuth, Admin.getAdminDelete);
router.get('/supplier', checkAuth, Supplier.getSupplier);
router.post('/adminsupplier', checkAuth, Supplier.postadminSupplier);
router.get('/adminsupplier', checkAuth, Supplier.getadminSupplier);
router.get('/admin', Admin.getadmin);
router.post('/supplier', checkAuth, Supplier.postSupplier);
router.get('/allsuppliers', checkAuth, Supplier.getAllSuppliers);
router.get('/allsuppliersadmin', checkAuth, Supplier.getAllSuppliersAdmin);
router.get('/forgotadminpassword', checkAuth, Account.forgotAdminPassword);
router.post('/forgotadminpassword', checkAuth, Account.PostforgotAdminPassword);
router.get('/adminchangepassword:id', checkAuth, Account.getAdminChangePassword);
router.post('/adminchangepassword:id', checkAuth, Account.postAdminChangePassword);
router.get('/forgotuserpassword', checkAuth, Account.getuserForgotPassword);
router.post('forgotuserpassword', checkAuth, Account.postuserForgotPassword);
router.post('/createuser', checkAuth, Account.postcreateUser);
router.get('/createuser', checkAuth, Account.getCreateUser);
router.get('/userlogin', User.getuserLogin);
router.get('/signupandsignin', checkAuth, User.getSignupandsignin);
router.post('/adminsearch', checkAuth, Admin.AdminSearch);
router.post('/allsuppliersadmin', checkAuth, Supplier.postAllsupplierAdmin);
router.post('/allusers', checkAuth, User.postAllusers);
router.post('/allsuppliers', checkAuth, Supplier.postAllsuppliers);
router.get('/viewpurchases', checkAuth, Purchases.getviewPurchases);
router.get('/usersdelete:id', checkAuth, User.usersDelete);
router.get('/debtorsdelete:id', checkAuth, Debtors.debtorsDelete);
router.get('/suppliersdelete:id', checkAuth, Supplier.getsuppliersDelete);
router.get('/printreceipt', checkAuth, Receipt.getPrintReceipt);
router.get('/printreceiptadmin', checkAuth, Receipt.printreceiptAdmin);
router.get('/search', checkAuth, Receipt.searchReciept);
router.get('/adminsearch', checkAuth, Receipt.adminReceipt);
router.post('/search', checkAuth, Search.postSearch);
router.post('/see', checkAuth, Admin.postSignUp);
router.post('/admin', Admin.logAdmin);
router.get('/adminhome', checkAuth, Admin.adminHome);
router.post('/accounteditinfo:id', checkAuth, Account.acccountEditId);
router.get('/accounteditinfo:id', checkAuth, Account.getAccountEdit);
router.get('/useraccountedit:id', checkAuth, User.userAccountEdit);
router.post('/useraccountedit:id', checkAuth, User.postuserAccountEdit);
router.get('/userpasswordchange:id', checkAuth, User.getuserPasswordChange);
router.post('/userpasswordchange:id', checkAuth, User.postuserPasswordChange);
router.get('/allusers', checkAuth, User.getAllUsers);
router.get('/admindailysales', checkAuth, Sales.adminGetDailySales);
router.get('/dailysales', checkAuth, Sales.getDailySales);
router.get('/logout', User.logout);
router.get('/delete:id', checkAuth, Purchases.deletePurchases);
router.get('/checkpage', checkAuth, User.checkPage);
router.get('/',RoleAuth, User.home);
router.get('/chat', checkAuth, chat.Chats);
module.exports = router;